import { makeStyles } from '@material-ui/core/styles';

const useStyles = makeStyles(() => ({
  root: {
    backgroundColor: '#332851',
    minHeight: '100vh',
    '& .MuiInput-underline:before': {
      position: 'relative',
      overwflow: 'hidden',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      cursor: 'pointer',
      flexDirection: 'column',
    },
  },
  pageWrapper: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexDirection: 'column',
    minHeight: '100vh',
    paddingTop: 0,
    paddingBottom: 0,
  },
  title: {
    fontFamily: 'Ubuntu',
    textTransform: 'uppercase',
    textAlign: 'center',
    fontSize: '30vw',
    fontWeight: 600,
    display: 'block',
    margin: 0,
    //color: '#9ae1e2',
    color: '#ca3074',
    position: 'relative',
    zIndex: 0,
    //animation: 'colors .4s ease-in-out forwards',
    //animationDelay: '1.7s',
    '& :before': {
      content: 'U',
      position: 'absolute',
      top: '-9%',
      right: '40%',
      transform: 'rotate(180deg)',
      fontSize: '15vw',
      color: '#f6c667',
      zIndex: -1,
      textAlign: 'center',
      //animation: 'lock .2s ease-in-out forwards',
      //animationDelay: '1.5s',
    },
  },
  subTitle: {
    fontFamily: 'Cabin',
    //color: '#9ae1e2',
    color: '#ca3074',
    fontSize: '5vw',
    fontWeight: 500,
    margin: 0,
    textTransform: 'uppercase',
    textAlign: 'center',
    //animation: 'colors .4s ease-in-out forwards',
    //animationDelay: '2s',
  },
  regularText: {
    fontFamily: 'Cabin',
    color: '#9ae1e2',
    fontSize: '2vw',
    margin: 0,
    textAlign: 'center',
    opacity: 1,
    //animation: 'show 2s ease-in-out forwards',
    //color: '#ca3074',
    //animationDelay: '3s',
  },
}));

export default useStyles;
